language: python
python:
  - "3.6"


services:
  - docker
  
before_install:
  - docker pull hello-world
  - docker run hello-world
  
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python main.py
